// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIJR6G5NcvHLUmZwTZ8TVtWzjl-gUErwE',
    appId: '1:972386783971:web:e67d0769316c78f90babd6',
    messagingSenderId: '972386783971',
    projectId: 'taskmanager-25632',
    authDomain: 'taskmanager-25632.firebaseapp.com',
    storageBucket: 'taskmanager-25632.firebasestorage.app',
    measurementId: 'G-35SDYC9062',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaB-bA0puhorViNltVH0lssHIw3WxBxmc',
    appId: '1:972386783971:android:ccdbed68e3f61b390babd6',
    messagingSenderId: '972386783971',
    projectId: 'taskmanager-25632',
    storageBucket: 'taskmanager-25632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1vigRhWZv4DG1nnxRpQdBPlWFIFxoXA',
    appId: '1:972386783971:ios:58c3d531755f4fc80babd6',
    messagingSenderId: '972386783971',
    projectId: 'taskmanager-25632',
    storageBucket: 'taskmanager-25632.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIJR6G5NcvHLUmZwTZ8TVtWzjl-gUErwE',
    appId: '1:972386783971:web:da5c972d0332b0dd0babd6',
    messagingSenderId: '972386783971',
    projectId: 'taskmanager-25632',
    authDomain: 'taskmanager-25632.firebaseapp.com',
    storageBucket: 'taskmanager-25632.firebasestorage.app',
    measurementId: 'G-F6DZZY177E',
  );
}
